declare const React: any;
declare const ReactDOM: any;
declare const _: any;
declare const $: any;
declare const log: any;
declare const Reflux: any;
declare const jsPlumb: any;
declare const gapi: any;
declare const google: any;
